# Generated by Django 3.2.8 on 2021-10-24 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_events_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='image',
        ),
    ]
